name: shoppy_go
description: Blueberry Project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.5.2+210

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  path_provider: ^2.0.11
  flutter_automation: ^2.0.0
  flutter_archive: ^5.0.0
  file_picker: ^5.2.2
  restart_app: ^1.1.0+1
  url_launcher: ^6.1.6
  pdf: ^3.8.4
  share: ^2.0.4

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/banner.png
    - assets/images/check.png
    - assets/icon/icon.png
    - assets/images/create_note.png
    - assets/images/read_notes.png
    - assets/images/add_product.png
    - assets/images/catalogo.png
    - assets/products/lacteos/egg.png
    - assets/products/lacteos/leche_entera.png
    - assets/products/lacteos/leche_desnatada.png
    - assets/products/lacteos/cheese.png
    - assets/products/lacteos/yogur.jpg
    - assets/products/lacteos/quesitos.png
    - assets/products/lacteos/flan.png
    - assets/products/lacteos/gelatina.png
    - assets/products/carnes/chicken.png
    - assets/products/carnes/pork.png
    - assets/products/carnes/serrano.jpg
    - assets/products/carnes/york.png
    - assets/products/carnes/solomillo.png
    - assets/products/frutas/manzana.png
    - assets/products/frutas/pera.png
    - assets/products/frutas/platanos.png
    - assets/products/frutas/kiwi.png
    - assets/products/frutas/mango.png
    - assets/products/frutas/coco.png
    - assets/products/frutas/melon.png
    - assets/products/frutas/sandia.png
    - assets/products/frutas/uvas.png
    - assets/products/frutas/ciruelas.png
    - assets/products/frutas/naranja.png
    - assets/products/frutas/mandarina.png
    - assets/products/frutas/fresas.jpg
    - assets/products/frutas/arandano.jpg
    - assets/products/frutas/paraguayo.jpg
    - assets/products/frutas/frambuesa.png
    - assets/products/frutas/piña.png
    - assets/products/frutas/granada.jpg
    - assets/products/frutas/lima.png
    - assets/products/verduras/limon.png
    - assets/products/verduras/puerro.png
    - assets/products/verduras/coliflor.png
    - assets/products/verduras/lechuga.png
    - assets/products/verduras/acelgas.jpg
    - assets/products/verduras/espinacas.jpg
    - assets/products/verduras/apio.png
    - assets/products/hortalizas/berenjena.png
    - assets/products/hortalizas/calabacino.png
    - assets/products/hortalizas/cebollas.png
    - assets/products/hortalizas/zanahorias.png
    - assets/products/hortalizas/pimientos.png
    - assets/products/hortalizas/calabaza.png
    - assets/products/hortalizas/tomate.png
    - assets/products/hortalizas/patatas.png
    - assets/products/pescados/lenguado.jpg
    - assets/products/pescados/lubina.jpg
    - assets/products/pescados/bacaladillas.jpg
    - assets/products/pescados/atun.png
    - assets/products/pescados/caballa.jpg
    - assets/products/pescados/calamar.png
    - assets/products/pescados/jurel.jpg
    - assets/products/pescados/sardina.jpeg
    - assets/products/pescados/bogavante.jpg
    - assets/products/pescados/trucha.png
    - assets/products/pescados/percebe.jpg
    - assets/products/pescados/rosada.png
    - assets/products/pescados/merluza.png
    - assets/products/pescados/boquerones.png
    - assets/products/shampoos/shampoo.png
    - assets/products/shampoos/gel.png
    - assets/products/higiene/colonia.png
    - assets/products/higiene/desodorante.png
    - assets/products/higiene/higienico.png
    - assets/products/higiene/jabon.png
    - assets/products/higiene/nenuco.jpg
    - assets/products/higiene/panales.jpg
    - assets/products/higiene/toallitas.png
    - assets/products/legumbres/alubias.png
    - assets/products/legumbres/garbanzos.png
    - assets/products/legumbres/lentejas.png
    - assets/products/pasta/macarrones.png
    - assets/products/pasta/espaguetis.png
    - assets/products/pasta/arroz.jpg
    - assets/products/pasta/fideos.jpg
    - assets/products/helados/helado.png
    - assets/products/refrescos/agua.png
    - assets/products/refrescos/aquarius.png
    - assets/products/refrescos/cocacola.png
    - assets/products/refrescos/fanta.jpg
    - assets/products/refrescos/kas.png
    - assets/products/refrescos/melocoton.jpg
    - assets/products/refrescos/nestea.png
    - assets/products/refrescos/sevenup.jpg
    - assets/products/refrescos/sprite.jpg
    - assets/products/refrescos/trina.png
    - assets/products/dulces/cereales.png
    - assets/products/dulces/donut.jpg
    - assets/products/dulces/oreo.png
    - assets/products/frutos_secos/almendras.png
    - assets/products/frutos_secos/avellana.jpg
    - assets/products/frutos_secos/cacahuetes.png
    - assets/products/frutos_secos/nueces.png
    - assets/products/frutos_secos/pipas.jpg
    - assets/products/frutos_secos/pistachos.png
    - assets/products/aperitivos/campesinas.jpg
    - assets/products/aperitivos/lays.jpg
    - assets/products/aperitivos/gusanitos.png
    - assets/products/aperitivos/pringles.png
    - assets/images/empty_basket.png
    - assets/images/empty_note.png
    - assets/products/lacteos/mantequilla.png
    - assets/products/dulces/galletas.png
    - assets/products/dulces/chocoflakes.jpg
    - assets/products/higiene/lejia.jpg
    - assets/products/higiene/detergente.png
    - assets/products/especias/harina.jpg
    - assets/products/especias/sal.png
    - assets/products/especias/azucar.png
    - assets/products/especias/bicarbonato.png
    - assets/products/frutas/mermelada.png
    - assets/products/dulces/chocolate.png
    - assets/products/pan/barra.jpg
    - assets/products/pan/bollos.png
    - assets/products/pan/molde.png
    - assets/products/frutas/pomelo.png
    - assets/products/frutas/membrillo.png
    - assets/products/vegetales/champinones.png
    - assets/products/vegetales/setas.jpg
    - assets/products/carnes/carne_picada.jpeg
    - assets/products/aceites/girasol.png
    - assets/products/aceites/oliva.jpg
    - assets/products/carnes/pate.png
    - assets/products/salsas/alioli.png
    - assets/products/salsas/ketchup.png
    - assets/products/salsas/mayonesa.png
    - assets/products/salsas/mostaza.png
    - assets/products/salsas/tomate.png
    - assets/products/refrescos/blanco.png
    - assets/products/refrescos/cerveza.png
    - assets/products/refrescos/vino.png
    - assets/products/congelados/croquetas.png
    - assets/products/congelados/flamenquines.jpg
    - assets/products/congelados/nuggets.png
    - assets/products/congelados/jacobos.jpg
    - assets/products/pan/rallado.png
    - assets/cards/amigos.png
    - assets/cards/barbacoa.png
    - assets/cards/carro.png
    - assets/cards/cine.png
    - assets/cards/rosa.png
    - assets/cards/tienda.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
